module.exports = {
  Author: require('./Author'),
  AuditLog: require('./AuditLog'),
  AuthToken: require('./AuthToken'),
  Book: require('./Book'),
  BookCopy: require('./BookCopy'),
  BorrowDetail: require('./BorrowDetail'),
  BorrowRequest: require('./BorrowRequest'),
  Category: require('./Category'),
  Fine: require('./Fine'),
  Member: require('./Member'),
  MembershipApplication: require('./MembershipApplication'),
  Notification: require('./Notification'),
  NotificationAttempt: require('./NotificationAttempt'),
  NotificationTemplate: require('./NotificationTemplate'),
  Publisher: require('./Publisher'),
  Reservation: require('./Reservation'),
  Role: require('./Role'),
  User: require('./User'),
  UserProfile: require('./UserProfile'),
  UserRole: require('./UserRole'),
};
